name: http_status_code
description: HTTP Status Codes
version: 0.0.2
repository: https://github.com/salkuadrat/http_status_code
homepage: https://github.com/salkuadrat/http_status_code

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies: