import 'status_code.dart';

Map<int, String> statusCodeMessages = {
  StatusCode.CONTINUE: 'Continue',
  StatusCode.SWITCHING_PROTOCOLS: 'Switching Protocols',
  StatusCode.PROCESSING: 'Processing',
  StatusCode.OK: 'OK',
  StatusCode.CREATED: 'Created',
  StatusCode.ACCEPTED: 'Accepted',
  StatusCode.NON_AUTHORITATIVE_INFORMATION: 'Non-Authoritative Information',
  StatusCode.NO_CONTENT: 'No Content',
  StatusCode.RESET_CONTENT: 'Reset Content',
  StatusCode.PARTIAL_CONTENT: 'Partial Content',
  StatusCode.MULTI_STATUS: 'Multi-Status',
  StatusCode.MULTIPLE_CHOICES: 'Multiple Choices',
  StatusCode.MOVED_PERMANENTLY: 'Moved Permanently',
  StatusCode.MOVED_TEMPORARILY: 'Moved Temporarily',
  StatusCode.SEE_OTHER: 'See Other',
  StatusCode.NOT_MODIFIED: 'Not Modified',
  StatusCode.USE_PROXY: 'Use Proxy',
  StatusCode.TEMPORARY_REDIRECT: 'Temporary Redirect',
  StatusCode.PERMANENT_REDIRECT: 'Permanent Redirect',
  StatusCode.BAD_REQUEST: 'Bad Request',
  StatusCode.UNAUTHORIZED: 'Unauthorized',
  StatusCode.PAYMENT_REQUIRED: 'Payment Required',
  StatusCode.FORBIDDEN: 'Forbidden',
  StatusCode.NOT_FOUND: 'Not Found',
  StatusCode.METHOD_NOT_ALLOWED: 'Method Not Allowed',
  StatusCode.NOT_ACCEPTABLE: 'Not Acceptable',
  StatusCode.PROXY_AUTHENTICATION_REQUIRED: 'Proxy Authentication Required',
  StatusCode.REQUEST_TIMEOUT: 'Request Timeout',
  StatusCode.CONFLICT: 'Conflict',
  StatusCode.GONE: 'Gone',
  StatusCode.LENGTH_REQUIRED: 'Length Required',
  StatusCode.PRECONDITION_FAILED: 'Precondition Failed',
  StatusCode.REQUEST_URI_TOO_LONG: 'Request-URI Too Long',
  StatusCode.UNSUPPORTED_MEDIA_TYPE: 'Unsupported Media Type',
  StatusCode.REQUESTED_RANGE_NOT_SATISFIABLE: 'Requested Range Not Satisfiable',
  StatusCode.EXPECTATION_FAILED: 'Expectation Failed',
  StatusCode.IM_A_TEAPOT: 'I\'m a Teapot',
  StatusCode.INSUFFICIENT_SPACE_ON_RESOURCE: 'Insufficient Space on Resource',
  StatusCode.METHOD_FAILURE: 'Method Failure',
  StatusCode.UNPROCESSABLE_ENTITY: 'Unprocessable Entity',
  StatusCode.LOCKED: 'Locked',
  StatusCode.FAILED_DEPENDENCY: 'Failed Dependency',
  StatusCode.PRECONDITION_REQUIRED: 'Precondition Required',
  StatusCode.TOO_MANY_REQUESTS: 'Too Many Requests',
  StatusCode.REQUEST_HEADER_FIELDS_TOO_LARGE: 'Request Header Fields Too Large',
  StatusCode.UNAVAILABLE_FOR_LEGAL_REASONS: 'Unavailable For Legal Reasons',
  StatusCode.INTERNAL_SERVER_ERROR: 'Internal Server Error',
  StatusCode.NOT_IMPLEMENTED: 'Not Implemented',
  StatusCode.BAD_GATEWAY: 'Bad Gateway',
  StatusCode.SERVICE_UNAVAILABLE: 'Service Unavailable',
  StatusCode.GATEWAY_TIMEOUT: 'Gateway Timeout',
  StatusCode.HTTP_VERSION_NOT_SUPPORTED: 'HTTP Version Not Supported',
};
